### ISSUE TITLE
field_order changes in written yuv4mpeg

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#12]
-YUV4MPEG2 W720 H480 F30000:1001 Ip A10:11 C411 XYSCSS=411
+YUV4MPEG2 W720 H480 F30000:1001 Ib A10:11 C411 XYSCSS=411

./ffmpeg -i tickets/2190/clip.yuv file-2190.y4m
input should be here: https://trac.ffmpeg.org/raw-attachment/ticket/2190/ticket2190-clip.tar.bz2

**Comment by dwbuiten** [comment]
Fixed.
