### ISSUE TITLE
Some mp3 files loose duration and bitrate

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#13]
An example fro the fate suite is:
./ffprobe-ref -show_format -prefix fate-suite/mp3-conformance/he_32khz.bit
duration=15.564405
size=95.760000 K
bit_rate=49.219000 K

vs.

duration=N/A
size=95.760000 K
bit_rate=N/A

**Comment by ghost** [comment]
Fixed by fe26912ce715c99de765f06e47f04a7708f24457.

Now it shows the same completely incorrect duration as ffmpeg 2.8.
