### ISSUE TITLE
holes in audio from mkv-ac3

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#14]
./ffmpeg-pre-codecpar -i tickets/2508/S09E01.\ Smallville\ -\ Savior\ -\ no\ audio\ sample.mkv -t 1 -vn -f framecrc -

http://samples.ffmpeg.org/ffmpeg-bugs/trac/ticket2508/

rsults in:
0,          0,          0,     1536,    18432, 0x00000000
0,       1536,       1536,     1536,    18432, 0x00000000
0,       3072,       3072,     1536,    18432, 0x00000000
0,       4608,       4608,     1536,    18432, 0x00000000
0,       6144,       6144,     1536,    18432, 0x00000000
0,       7680,       7680,     1536,    18432, 0x00000000
0,       9216,       9216,     1536,    18432, 0x00000000
0,      10752,      10752,     1536,    18432, 0x00000000
0,      12288,      12288,     1536,    18432, 0x00000000
0,      13824,      13824,     1536,    18432, 0x00000000
0,      15360,      15360,     1536,    18432, 0x00000000
0,      16896,      16896,     1536,    18432, 0x00000000
0,      18432,      18432,     1536,    18432, 0x00000000
0,      19968,      19968,     1536,    18432, 0x00000000
0,      21504,      21504,     1536,    18432, 0x00000000
0,      23040,      23040,     1536,    18432, 0x00000000
0,      24576,      24576,     1536,    18432, 0x00000000
0,      26112,      26112,     1536,    18432, 0x00000000
0,      27648,      27648,     1536,    18432, 0x00000000
0,      29184,      29184,     1536,    18432, 0x00000000
0,      30720,      30720,     1536,    18432, 0x00000000
0,      32256,      32256,     1536,    18432, 0x00000000
0,      33792,      33792,     1536,    18432, 0x00000000
0,      35328,      35328,     1536,    18432, 0x00000000
0,      36864,      36864,     1536,    18432, 0x00000000
0,      38400,      38400,     1536,    18432, 0x00000000
0,      39936,      39936,     1536,    18432, 0x00000000
0,      41472,      41472,     1536,    18432, 0x00000000
0,      43008,      43008,     1536,    18432, 0x00000000
0,      44544,      44544,     1536,    18432, 0x00000000
0,      46080,      46080,     1536,    18432, 0x00000000
0,      47616,      47616,      384,     4608, 0x00000000

vs. 
with codecpar:
0,          0,          0,     1536,    18432, 0x00000000
0,       9216,       9216,     1536,    18432, 0x00000000
0,      18432,      18432,     1536,    18432, 0x00000000
0,      27648,      27648,     1536,    18432, 0x00000000
0,      36864,      36864,     1536,    18432, 0x00000000
0,      46080,      46080,     1536,    18432, 0x00000000

**Comment by ghost** [comment]
This file isn't even valid, and there's a shitty hack in the mkv demuxer to "make" it work.

**Comment by ghost** [comment]
Fixed, it was indeed the shitty hack, which I accidentally broke when updating the mkv demuxer the first time.

**Comment by ghost** [comment]
PS: in 465499e982545ad91fa10483f1b1dead6ad8b4d9
