### ISSUE TITLE
dimensions of teletext stream disappears

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#15]
./ffprobe part.ts
http://samples.ffmpeg.org/ffmpeg-bugs/trac/ticket2471/part.ts

Stream #0:2[0x240](eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250

vs.

Stream #0:2[0x240](eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)

**Comment by ghost** [comment]
ffmpeg 2.8:

```
    Stream #0:2[0x240](eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250
    Stream #0:6[0x247](eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
```

codecpar:

```
    Stream #0:2[0x240](eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250
    Stream #0:6[0x247](eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
```

Works for me, but required compiling with libzvbi.
