### ISSUE TITLE
Displayed information about closed captions disappears

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#16]
./ffmpeg -i tickets/2147/sample.mpg

https://trac.ffmpeg.org/raw-attachment/ticket/2147/sample.mpg

there are also new frame sync errors in this file

[ac3 @ 0x1faeec0] frame sync error
[ac3 @ 0x1fb2180] frame sync error
...
Stream #0:2[0x1e0]: Video: mpeg2video (Main), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn

vs.

Stream #0:2[0x1e0]: Video: mpeg2video (Main), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, max. 20000 kb/s, 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc

**Comment by Nevcairiel** [comment]
The CC information display is a huge hack and likely to remain invisible. Containers do not signal the presence.

**Comment by michaelni** [comment]
if its just the display that is broken (i hope so) then this sounds like this could be ignored.
Is there a way to mark a issues as unimportant ?

**Comment by dwbuiten** [comment]
AC3 warnings fixed: https://github.com/dwbuiten/FFmpeg/commit/2946155e2eefbfabc8252a02dab981ce2dbf60a1
