### ISSUE TITLE
assertion failure in mov

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#17]
./ffmpeg -i tickets/236/fcp_export8.mov -codec copy -map 0 out.mov

https://trac.ffmpeg.org/raw-attachment/ticket/236/fcp_export8.mov
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
  Stream #0:3 -> #0:3 (copy)
  Stream #0:4 -> #0:4 (copy)
Press [q] to stop, [?] for help
Assertion c > 0 failed at libavutil/mathematics.c:61
Aborted

**Comment by dwbuiten** [comment]
Fixed. :cry:
