### ISSUE TITLE
pulse input broken

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#18]
./ffmpeg -f pulse -i default -t 0.1  wut.mp3
results in:
[pulse @ 0x2700ac0] Could not find codec parameters for stream 0 (Unknown: none): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, pulse, from 'default':
  Duration: N/A, start: 1459702634.708732, bitrate: N/A
    Stream #0:0: Unknown: none
Output #0, mp3, to 'wut.mp3':
Output file #0 does not contain any stream

vs:
./ffmpeg-pre-codecpar -f pulse -i default -t 0.1  wut2.mp3
Guessed Channel Layout for  Input Stream #0.0 : stereo
Input #0, pulse, from 'default':
  Duration: N/A, start: 1459702650.719545, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
Output #0, mp3, to 'wut2.mp3':
  Metadata:
    TSSE            : Lavf57.28.100
    Stream #0:0: Audio: mp3 (libmp3lame), 48000 Hz, stereo, s16p
    Metadata:
      encoder         : Lavc57.27.101 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
size=       2kB time=00:00:00.12 bitrate= 168.0kbits/s speed=0.759x  
video:0kB audio:2kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 10.286458%

**Comment by ghost** [comment]
Converted it, didn't check whether it actually works.

Please do such fixes yourself next time.
