### ISSUE TITLE
missing extradata in aac/m4a

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#19]
./ffmpeg -i tickets/3715/foo.aac -c copy -bsf:a aac_adtstoasc -t 0.1 foo.m4a
./ffmpeg -i foo.m4a -c copy -f framecrc -

file should be here: https://trac.ffmpeg.org/raw-attachment/ticket/3715/foo.aac

previously shows 
# extradata 0:        2, 0x00340022

**Comment by dwbuiten** [comment]
Fixed.
