### ISSUE TITLE
wrong duration with aac input

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#25]
./ffmpeg -i tickets/3312/ref.aac  -t 1 ref.wav
generates a output thats about twice as long as it should be

https://samples.mplayerhq.hu/ffmpeg-bugs/trac/ticket3312/ref.aac
it also produces a stream of 
[wav @ 0x3c1ca00] Non-monotonous DTS in output stream 0:0; previous: 41983, current: 6144; changing to 41983. This may result in incorrect timestamps in the output file.
 warnings

**Comment by dwbuiten** [comment]
Looks related to the (awful) timestamp generation code. I'll check.

(also the output wav files are identical without -t 1)

**Comment by dwbuiten** [comment]
Fixed.
