### ISSUE TITLE
ffserver segfault #2

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#27]
valgrind --trace-children=yes ./ffserver_g -f tests/ffserver.conf
==982== Invalid read of size 4
==982==    at 0x53D182: avformat_write_header (in /home/michael/ffmpeg-git/ffmpeg/ffserver_g)
==982==    by 0x4849B0: main (in /home/michael/ffmpeg-git/ffmpeg/ffserver_g)
==982==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==982== 
==982== 
==982== Process terminating with default action of signal 11 (SIGSEGV)
==982==  Access not within mapped region at address 0x0
==982==    at 0x53D182: avformat_write_header (in /home/michael/ffmpeg-git/ffmpeg/ffserver_g)
==982==    by 0x4849B0: main (in /home/michael/ffmpeg-git/ffmpeg/ffserver_g)

**Comment by dwbuiten** [comment]
What conf file does this use? I cannot reproduce it.

Edit: Im dumb, it is in tests.

**Comment by dwbuiten** [comment]
Fixed.
