### ISSUE TITLE
Starship_Troopers.vob doesnt show subtitles anymore

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#28]
testable with ffplay
./ffplay tickets/1332/Starship_Troopers.vob

file should be at http://samples.mplayerhq.hu/MPEG-VOB/ClosedCaptions/Starship_Troopers.vob

it also shows new warnings
[mpeg @ 0x7f259c0008c0] Could not find codec parameters for stream 5 (Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpeg @ 0x7f259c0008c0] Could not find codec parameters for stream 6 (Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
...
No codec could be found with id 0

**Comment by Nevcairiel** [comment]
I don't have ffplay setup due to SDL, but can you test the latest code? I think I fixed it - in various steps. Two bugs causing the wrong error message, and one bug preventing ffmpeg/ffplay from seeing the stream.

**Comment by michaelni** [comment]
Confirm, its fixed
thanks
