### ISSUE TITLE
9fcfda19437d72959572d2e1e16673d07f8922b4 breaks fate/movenc

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#29]
--- ./tests/ref/fate/movenc 2016-04-05 09:19:19.254510959 +0200
+++ tests/data/fate/movenc  2016-04-05 09:30:42.218525347 +0200
@@ -9,12 +9,16 @@
 3ece148745cd64b4428530a4d1080a2d 3203 delay-moov-elst
 9562946a369e6fb570fb2fd7aa2fe728 2098 delay-moov-empty-track
 4c7832b81836331c6c37155dc31d95be 2001 delay-moov-empty-track-flush
-b7e3c768b9094ebe2fda44979a7f8985 1159 empty-moov-header
-a0165f4a26a409212b0946e981bdefb9 1584 empty-moov-content
+d41d8cd98f00b204e9800998ecf8427e 0 empty-moov-header
+237504bcc68636af8edf7f1dacec28b9 2743 empty-moov-content
 b7e3c768b9094ebe2fda44979a7f8985 1159 delay-moov-header
+506: delay_moov header differs from empty_moov
+509: Manually flushed content differs from automatically flushed, 796 vs 1955
 a0165f4a26a409212b0946e981bdefb9 1584 delay-moov-content
+513: delay_moov content differs from empty_moov
 272a474cfd2a68cc5f05b426b14a2b7d 876 empty-moov-second-frag
-272a474cfd2a68cc5f05b426b14a2b7d 876 empty-moov-second-frag-discont
+e2cf1185f1af15057d32f32af58fa5fa 2023 empty-moov-second-frag-discont
+543: discontinuously written fragment differs
 272a474cfd2a68cc5f05b426b14a2b7d 876 delay-moov-second-frag-discont
 6ec3698bcc86013e0016e3d47d230363 1219 delay-moov-elst-init
 fcae8f40e015b59aabc8d4a99a759ca1 996 delay-moov-elst-second-frag

**Comment by Nevcairiel** [comment]
This seems annoying, the unit test relies on having avformat_write_header actually write header data, while the commit in question delays this, which has no real-world impact that I can think of, but breaks the tests in various ways.

**Comment by dwbuiten** [comment]
It does affect the DASH API, which I personally use.

Luckily, the autobsf conversion of mov/mp4 is not _required_ for codecpar, and I can just move it to a different WIP branch for cleanup before I submit to the ML.

Closing for now.
