### ISSUE TITLE
060aaffaa43d986a06753683a507839a431714da breaks fate-ts-opus-demux

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#32]
--- ./tests/ref/fate/ts-opus-demux  2016-04-08 13:20:51.472276905 +0200
+++ tests/data/fate/ts-opus-demux   2016-04-08 13:20:59.076277065 +0200
@@ -1,4 +1,3 @@
-#extradata 0:       30, 0x53be0347
 #tb 0: 1/90000
 0,          0,          0,     1800,      744, 0x172b615b, S=1,        1, 0x00bd00bd
 0,       1800,       1800,     1800,      743, 0x3f5b673d, S=1,        1, 0x00bd00bd

**Comment by Nevcairiel** [comment]
mpegts really doesn't like the codecpar approach combined with the probe decoder.
Fixed, but hopefully nothing else breaks.
