### ISSUE TITLE
duration is slightly off

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#33]
./ffmpeg  -i matrixbench_mpeg2.mpg  -t 1 t1.mkv
./ffprobe  t1.mkv

Stream #0:0: Video: h264 (High), yuv420p, 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc57.33.100 libx264
      DURATION        : 00:00:01.00300000

vs.
Stream #0:0: Video: h264 (High), yuv420p, 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc57.33.100 libx264
      DURATION        : 00:00:00.963000000

**Comment by michaelni** [comment]
I think this represents a significant number of the one/few byte differences ive seen/mentioned

**Comment by ghost** [comment]
What do byte differences have to do with duration differences?

**Comment by richardpl** [comment]
And real duration is?

**Comment by michaelni** [comment]
On Fri, Apr 08, 2016 at 06:26:43AM -0700, V. Lang wrote:

> What do byte differences have to do with duration differences?

I had mentioned byte differences in the output files o IRC IIRC
this difference in the duration seems to be the cause of most of the
output file byte differences that i had seen

## 

Michael     GnuPG fingerprint: 9FF2128B147EF6730BADF133611EC787040B0FAB

The misfortune of the wise is better than the prosperity of the fool.
-- Epicurus

**Comment by michaelni** [comment]
the real duration should be 1 second due to -t 1
there are also 25 frames stored and decoded, it just seems some duration "metadata" is off
