### ISSUE TITLE
12bit mjpeg fails

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#4]
./ffplay tickets/4683/12bpp.jpg

looks quite bad, seems to be ok before the codecpar stuff
sameple at: https://trac.ffmpeg.org/raw-attachment/ticket/4683/12bpp.jpg

**Comment by dwbuiten** [comment]
Sample?

**Comment by michaelni** [comment]
i think the 12 bits per sample are lost somewhere

**Comment by michaelni** [comment]
i see: (but maybe unrelated)
Stream #0:0: Video: mjpeg, gray16le(12 bpc, bt470bg/unknown/unknown), 999x749 [SAR 300:300 DAR 999:749], 25 tbr, 25 tbn, 25 tbc
vs.
Stream #0:0: Video: mjpeg, gray16le(bt470bg/unknown/unknown), 999x749 [SAR 300:300 DAR 999:749], 25 tbr, 25 tbn

**Comment by michaelni** [comment]
this issue disappears if avctx->bits_per_raw_sample = 12; is set at the top of mjpeg decoder init

**Comment by michaelni** [comment]
this might be a issue unrelated to codec par, iam not sure yet

**Comment by michaelni** [comment]
Not an issue in codec par, ill push a fix to master
