### ISSUE TITLE
less informative stream/codec information displayed

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#5]
for example:
https://trac.ffmpeg.org/raw-attachment/ticket/3348/test.ts
shows with codecpar
Stream #0:1[0x45]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv), 704x576 [SAR 16:11 DAR 16:9], 25 fps, 25 tbr, 90k tbn
before:
Stream #0:1[0x45]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv), 704x576 [SAR 16:11 DAR 16:9], max. 15000 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc

This is of course only a minor issue

**Comment by jamrial** [comment]
Same thing with fate-suite/flash-vp6/300x180-Scr-f8-056alpha.flv (used by fate-vp6a-skip_alpha and fate-vp6a).

**Before:**
Input #0, flv, from '../samples/flash-vp6/300x180-Scr-f8-056alpha.flv':
  Metadata:
    audiodelay      : 0
    canSeekToEnd    : 1
    creationdate    : Mon Aug 13 12:37:55 2007
                    :
  Duration: 00:00:23.00, start: 0.000000, bitrate: 51 kb/s
    Stream #0:0: Video: vp6a, yuv420p, 300x180, 49 kb/s, 4 fps, 4 tbr, 1k tbn, 1k tbc

**After:**
[flv @ 0000026833ff8c80] video stream discovered after head already parsed
Input #0, flv, from '../samples/flash-vp6/300x180-Scr-f8-056alpha.flv':
  Metadata:
    audiodelay      : 0
    canSeekToEnd    : 1
    creationdate    : Mon Aug 13 12:37:55 2007
                    :
  Duration: 00:00:23.00, start: 0.000000, bitrate: 51 kb/s
    Stream #0:0: Video: vp6a, yuva420p, 300x180, 4 fps, 4 tbr, 1k tbn

**Comment by dwbuiten** [comment]
EDIT: WRONG THREAD
