### ISSUE TITLE
encoding with xvid to mov fails

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#6]
./ffmpeg -f lavfi -i testsrc -vcodec libxvid -vframes 2   file.mov
resulting file is not playable
xvid in avi works
smells like extradata / global header related

**Comment by dwbuiten** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2016-April/192526.html

**Comment by dwbuiten** [comment]
Closing since patch is on ML.
