### ISSUE TITLE
tmcd timebase

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#7]
./ffprobe -v 50 timecode_in_counter_mode.mov
http://samples.ffmpeg.org/mov/timecode_in_counter_mode.mov
shows
Stream #0:2(eng), 0, 1/48: Data: none (tmcd / 0x64636D74), 0/1, 0 kb/s (default)
previously:
Stream #0:2(eng), 0, 1/48: Data: none (tmcd / 0x64636D74), 1/48, 0 kb/s (default)

If its just a difference in the printout then its minor of course, i did not investigate if its just the printout

**Comment by dwbuiten** [comment]
Confirmed this is a printout issue only.

**Comment by dwbuiten** [comment]
Looks like this is actually expected, since how tmcd does not set the codec timebase.
