### ISSUE TITLE
EAC3 in mpeg-ps detection fails

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#8]
http://samples.ffmpeg.org/ffmpeg-bugs/roundup/issue1499/hpim0054.mpg
before:
[NULL @ 0x7f0e180030c0] start time for stream 0 is not set in estimate_timings_from_pts
[NULL @ 0x7f0e18008ce0] start time for stream 1 is not set in estimate_timings_from_pts
[mpeg @ 0x7f0e180008c0] Could not find codec parameters for stream 1 (Audio: ac3, 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpeg, from '/home/michael/issues/1499/hpim0054.mpg':
  Duration: 00:00:13.96, start: 0.122878, bitrate: 6229 kb/s
    Stream #0:0[0x80]: Audio: eac3, 32000 Hz, 3.0(back), fltp, 1676 kb/s
    Stream #0:1[0xc2]: Audio: ac3, 0 channels
    Stream #0:2[0x1e0]: Video: mpeg1video, yuv420p(tv), 640x480 [SAR 1:1 DAR 4:3], 104857 kb/s, 24 fps, 24 tbr, 90k tbn, 24 tbc
    Stream #0:3[0x1c0]: Audio: mp2, 44100 Hz, mono, s16p, 96 kb/s

after:

[ac3 @ 0x7fe280003660] frame sync errorvq=    0KB sq=    0B f=0/0  
[ac3 @ 0x7fe280003660] Additional substreams is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[ac3 @ 0x7fe280003660] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[ac3 @ 0x7fe280003660] unsupported frame type : skipping frame
[mpeg @ 0x7fe2800008c0] decoding for stream 0 failed
[mpeg @ 0x7fe2800008c0] start time for stream 0 is not set in estimate_timings_from_pts
[mpeg @ 0x7fe2800008c0] start time for stream 1 is not set in estimate_timings_from_pts
[mpeg @ 0x7fe2800008c0] Could not find codec parameters for stream 0 (Audio: mp2, 44100 Hz, mono, s16p, 96 kb/s): unspecified number of channels
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpeg @ 0x7fe2800008c0] Could not find codec parameters for stream 1 (Audio: mp2, 44100 Hz, mono, s16p, 96 kb/s): unspecified sample format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpeg, from '/home/michael/issues/1499/hpim0054.mpg':
  Duration: 00:00:13.96, start: 0.122878, bitrate: 6229 kb/s
    Stream #0:0[0x80]: Audio: ac3, 32000 Hz, 0 channels, fltp
    Stream #0:1[0xc2]: Audio: ac3, 0 channels
    Stream #0:2[0x1e0]: Video: mpeg1video, yuv420p(tv), 640x480 [SAR 1:1 DAR 4:3], 104857 kb/s, 24 fps, 24 tbr, 90k tbn
    Stream #0:3[0x1c0]: Audio: mp2, 44100 Hz, mono, s16p, 96 kb/s

**Comment by dwbuiten** [comment]
FIxed.
