### ISSUE TITLE
Duplicate aspect ratio displayed

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#9]
I dont know if its just the display or something deeper
but a file created by (with any ffmpeg version)
./ffmpeg-ref -i fate-suite/mpeg2/mpeg2_field_encoding.ts -s 200x200 test2.avi

shows duplicate aspect when viewed with codecpar ffprobe:
Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 200x200 [SAR 4:3 DAR 4:3], 400 kb/s, SAR 4:3 DAR 4:3, 25 fps, 25 tbr, 25 tbn

vs.

ref:
Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 200x200 [SAR 4:3 DAR 4:3], 400 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc

**Comment by Nevcairiel** [comment]
Not sure where these suddenly come from. The first is codec AR and the second is stream AR. MPEG-TS should have no stream AR so something must be setting it to the codec AR that previously did not. Odd.

**Comment by dwbuiten** [comment]
Fixed,
